version: "3.7"
services:
  mm2:
    env_file: .env
    restart: always
    build: 
      context: mm2
      dockerfile: Dockerfile
    volumes:
      - ./mm2:/mm2
    ports:
      - 7783:7783
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  dashboard:
    env_file: .env
    restart: always
    build: 
      context: dashboard
      dockerfile: Dockerfile
    volumes:
      - ./dashboard:/dashboard
    ports:
      - 3000:3000
    depends_on:
      - mm2
      - db
      - api
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  api:
    env_file: .env
    restart: always
    build: 
      context: api
      dockerfile: Dockerfile
    volumes:
      - ./api:/api
    ports:
      - 8081:8081
    depends_on:
      - mm2
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  db:
    env_file: .env
    restart: always
    image: timescale/timescaledb-ha:pg14-latest
    volumes:
      - /data/timescaledb:/var/lib/postgresql/data
    ports: 
      - 5432:5432
